seed: 1441
duration: 70.857
bpm: 120
streams:
- stream_id: stream4
  duration: 70.857
  sample: 002-20_5-3_0.wav
  time_mode: normalized
  distribution_mode: uniform
  fill_factor:
    type: cubic
    points: [[0, 2], [0.0926, 2.01], [0.1631, 0.46], [0.2586, 0.4], [0.3133, 2.75],
      [1, 1]]
  distribution: 1
  grain:
    duration: [[0, 0.02, step], [0.3433, 0.0032], [1, 0.02]]
    duration_range: 0
    envelope: rexporise
  pointer:
    start: 0
    speed_ratio: 0.01
    loop_unit: normalized
  pitch:
    ratio: 0.3
  pan: -60
  pan_range: 100
  volume: 0
  voices:
    num_voices: 4
    scatter: 1
    pitch:
      step: 0.3
      strategy: step
      unit: ratio
