seed: 1441
duration: 249.225
bpm: 120
streams:
- stream_id: stream9
  duration: 249.225
  sample: 001-47_0-15_0.wav
  time_mode: normalized
  distribution_mode: uniform
  fill_factor: 4
  distribution: 1
  grain:
    duration: [[0, 0.0004], [0.3493, 0.0007], [0.6645, 0.011]]
    duration_range: 0.001
    envelope: rectangle
    read_direction: [[0, 1], [0.07707, -1], [0.09393, 1], [0.11645, -1], [0.14403,
        1], [0.2061, 1], [0.25155, -1], [0.25921, 1], [0.25921, -1]]
  pointer:
    start: 0
    speed_ratio: 0.1
    loop_unit: normalized
    offset_range: 0.01
  pitch:
    ratio: 1
    range: 0
  pan: 0
  pan_range: 360
  volume: [[0, -36], [0.1, -9]]
  voices:
    num_voices: 2
    pitch:
      pitch_range: 0.5
      strategy: range
      unit: ratio
    pan:
      spread: 120
      strategy: stochastic
