seed: 1441
duration: 78.367
bpm: 120
streams:
- stream_id: stream8
  duration: 78.367
  sample: 001-3_0-5_5.wav
  time_mode: normalized
  distribution_mode: uniform
  fill_factor: 4
  distribution: 1
  grain:
    duration:
      type: cubic
      points: [[0, 0.001], [0.0227, 0.0013], [0.0586, 0.0055], [0.0783, 0.0021], [
          0.1813, 0.0016], [0.2581, 0.003], [0.3182, 0.0089], [0.3616, 0.0056], [
          0.4059, 0.0021], [0.4611, 0.0038], [0.4857, 0.0061], [0.5325, 0.0102], [
          0.5586, 0.0056], [0.5744, 0.0038], [0.5872, 0.0023]]
    duration_range: 0.001
    envelope: hanning
    read_direction: [[0, 1], [0.07707, -1], [0.09393, 1], [0.11645, -1], [0.14403,
        1], [0.2061, 1], [0.25155, -1], [0.25921, 1], [0.25921, -1]]
  pointer:
    start: 0
    speed_ratio: 0.1
    loop_unit: normalized
    offset_range: 0.02
  pitch:
    ratio: 0.5
    range: 0.02
  pan: -90
  pan_range: 360
  volume: -3
  voices:
    num_voices: 1
    pitch:
      pitch_range: 0.2
      strategy: stochastic
      unit: ratio
